### ISSUE TITLE
README 里面的 `Usage` 会导致循给自己发消息

### ISSUE THREAD

**Issue by Anson2048** [feit/Weixinbot#4]
代码写的很好，很有启发性。我有两个建议。

-  `Usage` 会有重复一直给自己发消息的逻辑。 你是不是应该加上一个登陆成功的事件，然后在登入成功之后给自己发一条消息。

- 代码当中包含了你邮箱的 `auth` 是不是应该为了安全考虑去掉去。

**Comment by feit** [comment]
有道理，应该判断一下新消息是不是来自自己，这个确实没有考虑到
登录成功这个事件会加，发送给自己登录成功的消息可以自己实现
这个邮箱就是为了方便大家测试，等腾讯给我发警告的时候再撤吧

**Comment by wfsovereign** [comment]
不仅循环给自己发消息，还有你已经发消息的那个人也是

weixinbot
      新消息
      <span class="emoji emoji1f525"></span>  F君.。: &lt;msg&gt;<br/>&lt;op id='1'&gt;<br/>&lt;username&gt;wxid_ronlb7c0fw9732&lt;/username&gt;<br/>&lt;/op&gt;<br/>&lt;/msg&gt;
     +2ms
<span class="emoji emoji1f525"></span>  F君.。: &lt;msg&gt;<br/>&lt;op id='1'&gt;<br/>&lt;username&gt;wxid_ronlb7c0fw9732&lt;/username&gt;<br/>&lt;/op&gt;<br/>&lt;/msg&gt;
  weixinbot
      新消息
      <span class="emoji emoji1f525"></span>  F君.。: &lt;msg&gt;<br/>&lt;op id='1'&gt;<br/>&lt;username&gt;wxid_ronlb7c0fw9732&lt;/username&gt;<br/>&lt;/op&gt;<br/>&lt;/msg&gt;
     +1ms
<span class="emoji emoji1f525"></span>  F君.。: &lt;msg&gt;<br/>&lt;op id='1'&gt;<br/>&lt;username&gt;wxid_ronlb7c0fw9732&lt;/username&gt;<br/>&lt;/op&gt;<br/>&lt;/msg&gt;
  weixinbot
      新消息
      小白: 我不会说英语的啦，你还是说中文吧。
     +3s
小白: 我不会说英语的啦，你还是说中文吧。
  weixinbot
      新消息
      小白: 我不会说英语的啦，你还是说中文吧。
     +4ms
小白: 我不会说英语的啦，你还是说中文吧。
  weixinbot
      新消息
      <span class="emoji emoji1f525"></span>  F君.。: &lt;msg&gt;<br/>&lt;op id='1'&gt;<br/>&lt;username&gt;wxid_ronlb7c0fw9732&lt;/username&gt;<br/>&lt;/op&gt;<br/>&lt;/msg&gt;
     +3ms
<span class="emoji emoji1f525"></span>  F君.。: &lt;msg&gt;<br/>&lt;op id='1'&gt;<br/>&lt;username&gt;wxid_ronlb7c0fw9732&lt;/username&gt;<br/>&lt;/op&gt;<br/>&lt;/msg&gt;
  weixinbot
